apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
spec:
  type: NodePort
  selector:
    app: {{SERVICE_NAME}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001   
      nodePort: 30081    
