apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  labels:
    app: {{SERVICE_NAME}}
spec:
  selector:
    app: {{SERVICE_NAME}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
